apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: workout-tracker-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: CLIENT_URL
              value: "http://localhost"
            - name: CLIENT_HTTPS_URL
              value: "https://localhost"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080