apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: default
data:
  DB_NAME: "workout_tracker"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  CLIENT_URL: "http://localhost"
  CLIENT_HTTPS_URL: "https://localhost"
